// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2cuDFUXxXegfBqeyzrcCDf
// Component: Ihxf3QEUzV
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 2cuDFUXxXegfBqeyzrcCDf/projectcss
import sty from "./PlasmicDocs.module.css"; // plasmic-import: Ihxf3QEUzV/css

export type PlasmicDocs__VariantMembers = {};
export type PlasmicDocs__VariantsArgs = {};
type VariantPropType = keyof PlasmicDocs__VariantsArgs;
export const PlasmicDocs__VariantProps = new Array<VariantPropType>();

export type PlasmicDocs__ArgsType = {};
type ArgPropType = keyof PlasmicDocs__ArgsType;
export const PlasmicDocs__ArgProps = new Array<ArgPropType>();

export type PlasmicDocs__OverridesType = {
  layer11?: p.Flex<"div">;
};

export interface DefaultDocsProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicDocs__RenderFunc(props: {
  variants: PlasmicDocs__VariantsArgs;
  args: PlasmicDocs__ArgsType;
  overrides: PlasmicDocs__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const [isLayer11Hover, triggerLayer11HoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_layer11: isLayer11Hover
  };

  return (
    <div
      data-plasmic-name={"layer11"}
      data-plasmic-override={overrides.layer11}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.layer11
      )}
      data-plasmic-trigger-props={[triggerLayer11HoverProps]}
    >
      {(triggers.hover_layer11 ? true : false) ? (
        <h3
          className={classNames(
            projectcss.all,
            projectcss.h3,
            projectcss.__wab_text,
            sty.h3__x82Zx
          )}
        >
          {"VOID\nPAPER"}
        </h3>
      ) : null}
      {(triggers.hover_layer11 ? true : false) ? (
        <h3
          className={classNames(
            projectcss.all,
            projectcss.h3,
            projectcss.__wab_text,
            sty.h3__vvTaP
          )}
        >
          {"VOIDPAPER"}
        </h3>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  layer11: ["layer11"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  layer11: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDocs__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDocs__VariantsArgs;
    args?: PlasmicDocs__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDocs__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicDocs__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicDocs__ArgProps,
          internalVariantPropNames: PlasmicDocs__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicDocs__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "layer11") {
    func.displayName = "PlasmicDocs";
  } else {
    func.displayName = `PlasmicDocs.${nodeName}`;
  }
  return func;
}

export const PlasmicDocs = Object.assign(
  // Top-level PlasmicDocs renders the root element
  makeNodeComponent("layer11"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicDocs
    internalVariantProps: PlasmicDocs__VariantProps,
    internalArgProps: PlasmicDocs__ArgProps
  }
);

export default PlasmicDocs;
/* prettier-ignore-end */
