// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2cuDFUXxXegfBqeyzrcCDf
// Component: IqSSF-3-Gh
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 2cuDFUXxXegfBqeyzrcCDf/projectcss
import sty from "./PlasmicVoidswap.module.css"; // plasmic-import: IqSSF-3-Gh/css

export type PlasmicVoidswap__VariantMembers = {};
export type PlasmicVoidswap__VariantsArgs = {};
type VariantPropType = keyof PlasmicVoidswap__VariantsArgs;
export const PlasmicVoidswap__VariantProps = new Array<VariantPropType>();

export type PlasmicVoidswap__ArgsType = {};
type ArgPropType = keyof PlasmicVoidswap__ArgsType;
export const PlasmicVoidswap__ArgProps = new Array<ArgPropType>();

export type PlasmicVoidswap__OverridesType = {
  layer31?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultVoidswapProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicVoidswap__RenderFunc(props: {
  variants: PlasmicVoidswap__VariantsArgs;
  args: PlasmicVoidswap__ArgsType;
  overrides: PlasmicVoidswap__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const [isLayer31Hover, triggerLayer31HoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_layer31: isLayer31Hover
  };

  return (
    <div
      data-plasmic-name={"layer31"}
      data-plasmic-override={overrides.layer31}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.layer31
      )}
      data-plasmic-trigger-props={[triggerLayer31HoverProps]}
    >
      {(triggers.hover_layer31 ? true : true) ? (
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          <React.Fragment>
            <React.Fragment>{""}</React.Fragment>
            {(triggers.hover_layer31 ? true : true) ? (
              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3__duzrD
                )}
              >
                {"VOID\nSWAP"}
              </h3>
            ) : null}
            <React.Fragment>{""}</React.Fragment>
          </React.Fragment>
        </div>
      ) : null}
      {(triggers.hover_layer31 ? true : false) ? (
        <h3
          className={classNames(
            projectcss.all,
            projectcss.h3,
            projectcss.__wab_text,
            sty.h3__rMhBs
          )}
        >
          {"VOIDSWAP"}
        </h3>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  layer31: ["layer31", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  layer31: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVoidswap__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVoidswap__VariantsArgs;
    args?: PlasmicVoidswap__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVoidswap__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicVoidswap__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicVoidswap__ArgProps,
          internalVariantPropNames: PlasmicVoidswap__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicVoidswap__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "layer31") {
    func.displayName = "PlasmicVoidswap";
  } else {
    func.displayName = `PlasmicVoidswap.${nodeName}`;
  }
  return func;
}

export const PlasmicVoidswap = Object.assign(
  // Top-level PlasmicVoidswap renders the root element
  makeNodeComponent("layer31"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicVoidswap
    internalVariantProps: PlasmicVoidswap__VariantProps,
    internalArgProps: PlasmicVoidswap__ArgProps
  }
);

export default PlasmicVoidswap;
/* prettier-ignore-end */
