// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2cuDFUXxXegfBqeyzrcCDf
// Component: X_iWq4AcxZ
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 2cuDFUXxXegfBqeyzrcCDf/projectcss
import sty from "./PlasmicSocials.module.css"; // plasmic-import: X_iWq4AcxZ/css

import IconsaxLineararrowleftIcon from "./icons/PlasmicIcon__IconsaxLineararrowleft"; // plasmic-import: krXfSJQBPw/icon

export type PlasmicSocials__VariantMembers = {};
export type PlasmicSocials__VariantsArgs = {};
type VariantPropType = keyof PlasmicSocials__VariantsArgs;
export const PlasmicSocials__VariantProps = new Array<VariantPropType>();

export type PlasmicSocials__ArgsType = {};
type ArgPropType = keyof PlasmicSocials__ArgsType;
export const PlasmicSocials__ArgProps = new Array<ArgPropType>();

export type PlasmicSocials__OverridesType = {
  group3?: p.Flex<"a">;
  svg?: p.Flex<"svg">;
  text?: p.Flex<"div">;
};

export interface DefaultSocialsProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSocials__RenderFunc(props: {
  variants: PlasmicSocials__VariantsArgs;
  args: PlasmicSocials__ArgsType;
  overrides: PlasmicSocials__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <a
      data-plasmic-name={"group3"}
      data-plasmic-override={overrides.group3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.group3
      )}
      href={"https://linktr.ee/voidbastardz" as const}
      target={"_blank" as const}
    >
      <IconsaxLineararrowleftIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Check socials"}
      </div>
    </a>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  group3: ["group3", "svg", "text"],
  svg: ["svg"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  group3: "a";
  svg: "svg";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSocials__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSocials__VariantsArgs;
    args?: PlasmicSocials__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSocials__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSocials__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSocials__ArgProps,
          internalVariantPropNames: PlasmicSocials__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSocials__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "group3") {
    func.displayName = "PlasmicSocials";
  } else {
    func.displayName = `PlasmicSocials.${nodeName}`;
  }
  return func;
}

export const PlasmicSocials = Object.assign(
  // Top-level PlasmicSocials renders the root element
  makeNodeComponent("group3"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicSocials
    internalVariantProps: PlasmicSocials__VariantProps,
    internalArgProps: PlasmicSocials__ArgProps
  }
);

export default PlasmicSocials;
/* prettier-ignore-end */
